### ISSUE TITLE
 plot_trace_dist missing kind="dot"

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-plots#31]
Currently, plot_trace_dist only supports KDEs and ECDFs.

**Comment by OriolAbril** [comment]
After #39 `plot_trace_dist` calls `plot_dist` to populate the left column, so this is redundant with #25 as adding histogram support to `plot_dist` will automatically add support for it in `plot_trace_dist`. Consequently, I am closing this issue to leave only #25 as tracker for the task.
