### ISSUE TITLE
Behaviour of aesthetics mapping for dimension subset

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-plots#33]
`arviz_plots.PlotCollection.generate_aes_dt` is the method that takes care of assigning the values given for an aesthetic to the different coordinate value combinations. If the aesthetic is mapped to a single dimension, everything is very clear.

If an aesthetic is mapped to multiple dimensions, everything is clear _as long as variables with these dimensions always have all of them_. Here is one example:

Take dimensions `team, field` with sizes `6, 2` respectively. If we map "y" to both team and field, then we get the following pairings:

| field\team | 0 | 1 | 2 | ...|
|---|---|---|---|---|
| 0| y[0] | y[1] | y[2] | ... |
| 1| y[6] | y[7] | y[8] | ... |

However, we can also find variables that have only the field dimension, and variables that have only the team dimension.
Currently, the variables with only the field dimension would get the two first elements in y paired to them, and the variables with only the team dimension would get the 6 first values paired to them.

Which is probably not what we want because then, the value in y[0] is assigned to either of:
* field[0] and team[0]
* field[0]
* team[0]

Is that ok? Or should variables with only a subset of the dimensions defined in a mapping get no mapping at all?

**Comment by aloctavodia** [comment]
Taking the first element as neutral seems like a very reasonable approach
