### ISSUE TITLE
Add plot_ess

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-plots#5]

**Comment by OriolAbril** [comment]
`ess` is already available in `arviz-stats` it is possible to implement this plot already

**Comment by OriolAbril** [comment]
Should we split that into `plot_ess` (local or quantile) and `plot_ess_evolution`? The first two are quite similar whereas the 3rd one has nothing to do (in terms of plotting).

**Comment by aloctavodia** [comment]
Yes, that makes sense.
