### ISSUE TITLE
Add plot_forest

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-plots#6]
Split the current plot_forest into two functions plot_forest (intervals)  this issue and plot_ridge (mountain-range kde-like) #7 

For list of dataset/inferencedata input we might need another loop strategy
NOTE: `__variable__`  only works for facetting right now, it is needed for this to work with aesthetics when there are multiple variables.

**Comment by OriolAbril** [comment]
closed by https://github.com/arviz-devs/arviz-plots/pull/34
