### ISSUE TITLE
Add plot_ridge

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-plots#7]
Split the current plot_forest in to plot_ridge (mountain-range kde-like) this issue and plot_forest (intervals) #6 }

~~For list of dataset/inferencedata input we might need another loop strategy
NOTE: `__variable__`  only works for facetting right now, it is needed for this to work with aesthetics when there are multiple variables.~~

**Comment by OriolAbril** [comment]
It will look very similar to `plot_forest` (already implemented) so it might be a good idea to start from there and once it is working try to refactor them to extract common parts and avoid duplication
