### ISSUE TITLE
Unused argument `extra_data` in `PlotCollection.map` 

### ISSUE THREAD

**Issue by imperorrp** [arviz-devs/arviz-plots#70]
Very minor issue, just something that caught my eye while looking through this function- the [`extra_data` argument](https://github.com/arviz-devs/arviz-plots/blob/main/src/arviz_plots/plot_collection.py#L938) doesn't seem to do anything. It's defined to None by default and defaults to `{}` if None [later](https://github.com/arviz-devs/arviz-plots/blob/main/src/arviz_plots/plot_collection.py#L1001). Not mentioned in the docstring either. Was there some intended incomplete functionality behind it?

**Comment by OriolAbril** [comment]
You can open a small PR to get rid of it. It was an idea for passing arbitrary data via `.map` but eventually we decided on processing `**kwargs` directly and subset xarray objects if any of the present kwargs matches the type.
